### ISSUE TITLE
Possible BUG: floor() function does not handle negative values correctly

### ISSUE THREAD

**Issue by hmf** [non/spire#494] opened 2015-08-10 12:55 UTC
As consequence of #491 I tried to make a workaround and seem to have struck on a error. The idea is to split a number into its whole and fraction parts. In this example I take a `Real` of `1.9999999` and expect the whole `1` and fraction `0.9999999`: 
```scala
    val n5 = Real(1.9999999)
    val n5a = n5.toDouble
    val w5 = n5.floor
    val l5 = n5 % w5
    val t5 = n5 / w5
    println(s"$n5a") // 1.9999999
    println(s"n = $n5") // 9007198804381029/4503599627370496
    println(s"w = $w5") // 1   <----------
    println(s"l = $l5") // 4503599177010533/4503599627370496
    println(s"l' = ${l5.toDouble}") // 0.9999998999999999
    println(s"t = $t5") // 9007198804381029/4503599627370496
    println(s"t' = ${t5.toDouble}") // 1.9999999
```

In  the test above this works as expected. In the next example we do the same but now we use a negative value `-1.9999999`:
```scala
    val n6 = Real(-1.9999999)
    val n6a = n6.toDouble
    val w6 = n6.floor
    val l6 = n6 % w6
    val t6 = n6 / w6
    println(s"$n6a") // -1.9999999
    println(s"n = $n6") // -9007198804381029/4503599627370496
    println(s"w = $w6") // -2   <----------
    println(s"l = $l6") // -9007198804381029/4503599627370496
    println(s"l' = ${l6.toDouble}") // -1.9999999
    println(s"t = $t6") // 9007198804381029/9007199254740992
    println(s"t' = ${t6.toDouble}") // 0.99999995
```
Notice how the values are not what we expect. The whole is `-2` (`w6`) instead of `1` and fraction is `-1.9999999` (`l6`) instead of `0.9999999`.  We also have the same problem if we use `Rational`:

```scala
    val n3 = Rational(BigInt("147566573892046929107"),BigInt("73786976294838206464"))
    val n3a = n3.toDouble
    val w3 = n3.floor
    val l3 = n3 % w3
    val t3 = n3 / w3
    println(s"$n3a") // 1.9999
    println(s"n = $n3") // 147566573892046929107/73786976294838206464
    println(s"w = $w3") // 1   <----------
    println(s"l = $l3") // 73779597597208722643/73786976294838206464
    println(s"l' = ${l3.toDouble}") // 0.9999
    println(s"t = $t3") // 147566573892046929107/73786976294838206464
    println(s"t' = ${t3.toDouble}") // 1.9999
    
    val n4 = Rational(BigInt("-147566573892046929107"),BigInt("73786976294838206464"))
    val n4a = n4.toDouble
    val w4 = n4.floor
    val l4 = n4 % w4
    val t4 = n4 / w4
    println(s"$n4a") // -1.9999
    println(s"n = $n4") // -147566573892046929107/73786976294838206464
    println(s"w = $w4") // -2   <----------
    println(s"l = $l4") // -147566573892046929107/73786976294838206464
    println(s"l' = ${l4.toDouble}") // -1.9999
    println(s"t = $t4") // 147566573892046929107/147573952589676412928
    println(s"t' = ${t4.toDouble}") // 0.99995
```

I have not figured out the problem. However a quick check shows that the sign is being checked in the case on `Inexact`.  So either this is incorrect or the problem is in the case of `Exact`.

**Comment by hmf** [comment] 2015-08-10 15:11
Possibly another issue but related. I am trying to handle the sign myself however:
```scala
println(s"NRootOps : ${n5.nroot(-2)}")
```
 is giving the error:
```scala
java.lang.IllegalArgumentException: nroot(-2)
```
So my question is, shouldn't `nroot` deal with negative values? If not should I file this as a bug?

**Comment by non** [comment] 2015-08-10 15:17
So, currently both `pow` and `nroot` want to be given non-negative values.

Obviously in cases where you have both methods you could imagine a negative value dispatching to the other method (and possibly throwing an exception in the case of `Int.MinValue`). So I don't think this is a bug, although I would definitely accept a feature request to improve things.

Part of the difficulty is that currently `NRoot[A]` doesn't directly have access to `pow`.

**Comment by tixxit** [comment] 2015-08-10 15:19
The `floor` function rounds towards -infinity, not 0! So, you should expect `SomeNumberType(-1.99999).floor` to be -2.

**Comment by tixxit** [comment] 2015-08-10 15:20
For example, `java.lang.Math.floor(-1.999)` gives `-2.0`.

**Comment by tixxit** [comment] 2015-08-10 15:35
Re: nroot not having access to pow: the problem is that it limits NRoot too much. For instance, we can implement `nroot` for `Algebraic`, but not `pow`, since, eg, `2.pow(s.sqrt)` is not algebraic, but transcendental. If you don't need `pow`, then using only `nroot` makes your code more general.

**Comment by tixxit** [comment] 2015-08-10 15:40
Oh no - I just realized we're talking about `pow` not `fpow` (D'Oh!). I don't see a good reason why `pow` couldn't live with `NRoot` too, if it helps.

**Comment by non** [comment] 2015-08-10 15:45
@tixxit I think the thing we would have to be careful about is making sure that `NRoot#pow` doesn't conflict with other `pow` methods, in terms of both type classes and also syntax.

**Comment by hmf** [comment] 2015-08-10 17:47
@tixxit You are absolutely correct. Obviously floor(-1.999999) is -2. What was I thinking? My apologies.

**Comment by tixxit** [comment] 2015-08-10 17:58
No worries - it is a mistake I have made numerous times before! Closing this issue, but feel free to open up a new issue for `nroot` with negative #s.

**Closed by tixxit** 2015-08-10 17:58 UTC

**Comment by hmf** [comment] 2015-08-10 18:01
@non @tixxit I am having trouble keeping up with you. I ask a little more patience. So If I am using a Real and I want to deal with exponents in the most general way, how should I go about it? In my case exponents are Real or Rational either positive or negative (all input is a Real). Need I use only pow or fpow? Do I have to use both pow/fpow and nroot to deal with rational and irrational exponents?

**Comment by hmf** [comment] 2015-08-10 18:06
@tixxit ok. I will open a new issue an place the question their. Thanks.

**Comment by non** [comment] 2015-08-10 18:09
@hmf If I were you I'd do something like this:

```scala
def mypow(base: Real, exponent: Rational): Real = {
  if (exponent.signum < 0) return mypow(base, -exponent).reciprocal
  val n = exponent.numerator
  val d = exponent.denominator
  require(n.isValidInt)
  require(d.isValidInt)
  base.pow(n.toInt).nroot(d.toInt)
}
```

**Comment by non** [comment] 2015-08-10 18:11
There are a few things to note:

1. This means that if you want to use a `Real` exponent you'll have to decide what precision you want.
2. That precision should take into account that powers/roots greater than `Int.MaxValue` aren't that tractable using computable reals.

Hope this helps!

**Comment by non** [comment] 2015-08-10 18:12
(You could also use the updated `.limitToInt` code in the issue I mentioned, which would be a bit less brittle than this example.)

**Comment by hmf** [comment] 2015-08-10 19:01
@non Thanks. Indeed it does help. I will use .limitToInt as soon as it is available. I do have some issues though and need to think this over more carefully. I think it better to post this as a question in the mailing list.
